### ISSUE TITLE
Userlist provider missing

### ISSUE THREAD

**Issue by ewallah** [h5p/moodle-mod_hvp#236]
The current Moodle versions have 2 additional GDPR functions: get_users_in_context & delete_data_for_users

See https://docs.moodle.org/dev/Privacy_API

**Comment by thomasmars** [comment]
Thanks for reporting this, I've created https://h5ptechnology.atlassian.net/browse/HFP-2553 for implementing the functions.

**Comment by golenkovm** [comment]
Hi H5P team,

As I can see https://h5ptechnology.atlassian.net/browse/HFP-2553 is still open as well as https://github.com/h5p/h5p-moodle-plugin/pull/298

Could you, please, provide ETA for this issue?

Thank you so much.

**Comment by ewallah** [comment]
> We take feedback very seriously and are dedicated to making H5P better every

- [ ] day
- [ ] month
- [ ] year

**Comment by falcon-git** [comment]
We've jokingly said that when H5P is in Moodle Core the H5P Core Team developers will have ~100 million users each. Now they probably service tens of millions each. We're not able to do all the things we very much wished we could do at the moment. It is not fun to have things like this not being handled, but the good news is that we're slowly and steadily able to [increase the size of the team](https://recruit.manpower.no/no/ledig-stilling?job=1031580&title=joubel-is-searching-for-a-web-developer-to-join-the-team).

Open source does come with some challenges, but we're doing our best and it looks bright. We hope most of you will have patience with us until we've added sufficient muscles to handle everything we want to handle.

Right now the team is working on accessibility improvements funded by H5P.com. After that we'll be working on a huge new super exciting project funded by a university until the end of January. We do take urgent issues in between, but this haven't reached the top of that list yet.
