### ISSUE TITLE
New language string for grade.php

### ISSUE THREAD

**Issue by Urpokarhu1** [h5p/moodle-mod_hvp#322]
Hello,

When you open a H5P activitys own report in Moodle from Grades -> click on the h5p activities title -> if it has no student submissions it says "Results for" and I wish that this hard coded thing would be changed so I could translate it.

it's in grade.php
$title = "Results for {$hvp->title}";

**Comment by thomasmars** [comment]
Thanks for the report, we would appreciate a pull request that fixes this.

**Comment by thomasmars** [comment]
The title string is now translatable, thanks.
