### ISSUE TITLE
Throwing dmlwriteexception error in language customisation settings

### ISSUE THREAD

**Issue by Anupamatd** [h5p/moodle-mod_hvp#336]
Throwing dmlwriteexception error in language customisation settings due to the language strings having uppercase.

The issue is because of the string change in commit [e3e3400](https://github.com/h5p/h5p-moodle-plugin/commit/e3e340043acbbda0521718738c9b04e35a3ead8a) 

We need to update the uppercase string with lowercase in the table tool_customlang.

The issue is only for below strings:
* reuseContent
* reuseDescription
* contentCopied

Thanks,
Anu

**Comment by thomasmars** [comment]
You can follow this issue at https://github.com/h5p/moodle-mod_hvp/issues/313
