### ISSUE TITLE
Serve cachedassets with cache control public and immutable

### ISSUE THREAD

**Issue by brendanheywood** [h5p/moodle-mod_hvp#338]
I believe that all the content stored in the cachedassets filearea can be considered public as it is general files pulled from the hvp content libraries and not hvp instance data. I think there is an opportunity to increase the cache ability of these files by:

* [ ] making them public + a long ttl
* [ ] marking them as immutable as their file name appears to be a content hash and should be unique
* [ ] cacheable, especially by intermediate reverse proxies like varnish / cdn's

**Comment by thomasmars** [comment]
sounds good :+1:

**Comment by brendanheywood** [comment]
thanks @jamie-catalyst and @thomasmars
