### ISSUE TITLE
embed.css and embed.js and not served properly / cached by cdn's

### ISSUE THREAD

**Issue by brendanheywood** [h5p/moodle-mod_hvp#339]
Both of these files are served directly from the source directory so are not optimally served:

```
embed.php:88:$PAGE->requires->css(new \moodle_url("{$root}/mod/hvp/embed.css"));
embed.php-89-$PAGE->requires->js(new \moodle_url("{$root}/mod/hvp/embed.js"));
```

Browsers don't cache these properly, so they always make a conditional 304 request, and additionally they don't have cache control public immutable so they don't get cached by reverse proxies / cdns

Actions:

* [ ] /mod/hvp/embed.css this file is very minimal, I think it should be bundled directly into /styles.css and then it will end up in the main moodle file and compress / versioned, and served with the correct caching headers for free. The css classes are name spaced so there is already no potential for clashes

* [ ] /mod/hvp/embed.js should be bundled as amd and then served through moodles javascript serving endpoint lib/javascript.php and again will get all the correct headers for free

https://docs.moodle.org/dev/Javascript_Modules

**Comment by thomasmars** [comment]
Sounds good, we would love a pull request for this.

**Comment by brendanheywood** [comment]
hi @thomasmars I was going to close this as the patch from @jamie-catalyst is now merged. But I'm a little unsure of the release policy and cadence: when will this make it into the stable branch? Do you close issues only once the release is shipped?

**Comment by thomasmars** [comment]
Hi @brendanheywood, we close issues once they are merged in, so closing this is fine. We can always reopen if we find any problems with it. We're currently working on an integration with the content hub, once this is implemented we'll go through the prs and issues to ensure they get included in the release.

**Comment by brendanheywood** [comment]
thanks @thomasmars - do you aim for a release cadence of once a month or once a quarter or is it ad hoc?

**Comment by thomasmars** [comment]
It's pretty much ad hoc. It depends on what features we're currently prioritizing, that could be content types or external connected systems, which does not warrant a release, or core changes, which typically results in updating all integrations followed by a release of the plugins. Ideally the release cadence should be more stable and in short iterations. We're currently working on the "H5P Contet Hub", a global repository for sharing content, which will result in a release for Moodle, hopefully this year or early next year.
