### ISSUE TITLE
Error when create an h5p type course presentation

### ISSUE THREAD

**Issue by jesmarquez** [h5p/moodle-mod_hvp#352]
Hi,

I am creating an H5P activity and when I choose type content Course Presentation, I got this message:

[field:group:coursepresentation:presentation]

By console show this:

TypeError: Cannot read property 'prototype' of undefined
InteractiveVideoEditor.prototype = Object.create(H5P.DragNBar.FormManager.prototype);

My environment:
moodle 3.5.6 
H5P 1.18

Thanks!

**Comment by dezglidden** [comment]
@jesmarquez have you by any chance found a work around for this?

**Comment by dezglidden** [comment]
I've opened an issue on the h5p-course-presentation repo https://github.com/h5p/h5p-course-presentation/issues/130

**Comment by jesmarquez** [comment]
> @jesmarquez have you by any chance found a work around for this?

Hi!
Yes I found a solution as follow:

1. I updated plugin H5P (last version)
2. I udated all instances type course presentation to last version
3. I downloaded the example in the site https://h5p.org/presentation (file with extension .h5p)
4. Some course in moodle I created a new activity H5P and imported file before mentioned

Ready!
