### ISSUE TITLE
Error adding interactivity to video in Moodle 3.7

### ISSUE THREAD

**Issue by 1katoda** [h5p/moodle-mod_hvp#354]
There have been issues in Moodle 3.7 with the plugin version 1.20 regarding adding interactivity to videos. Instead of the toolbar, there is only `[field:group:interactiveVideo:assets]`, while the following errors appear in console:
```
Uncaught TypeError: H5P.DragNBar.FormManager is undefined
Uncaught TypeError: H5PEditor.InteractiveVideo is undefined
```
  
![hvp_error_display](https://user-images.githubusercontent.com/38652146/86571960-8febe580-bf72-11ea-8f7f-b2705d74dae9.png)

Are those 2 features not present in 1.20? When trying to upload an example .h5p file from h5p.org, the H5P editor field shows errors sugesting one must have the version newer than 1.23 for DragNBar functionality and a version newer than 1.24 for Interactive Video Editor.

The problem is, the latest version on Moodle Plugins and here on Github is 1.20. 

Any ideas as to what is happening and/or possible fixes?

**Comment by thomasmars** [comment]
The library is referring to h5p-core, not the h5p plugin version. Please download and install the latest h5p plugin version and then try to upload the latest libraries from h5p.org.

**Comment by 1katoda** [comment]
You are right, unnecessary mistake on my part, sorry.
