### ISSUE TITLE
Cannot edit or create Question sets or Columns - throws errors

### ISSUE THREAD

**Issue by BirdyOz** [h5p/moodle-mod_hvp#357]
**Environment:**  Moodle 3.9, running latest H5P plugin (2020020500) and latest libraries (refreshed nightly, via CRON)

**Summary:** At some point last week, certain H5P activity types such as Question Set (1.17.2) and Column Column (1.12.0) stopped being editable and started throwing errors (details lower).   These activities have dependencies on other libraries.

You can no longer create new activities of these same types.  

**Steps to replicate #1 - Editing an existing H5P **
**Sample H5P** https://www.dropbox.com/t/7xZS7sEIStCn2CUQ

1. Access an existing quiz (question set) or column activity

2.  Note that the activity is FAD

3.  Attempt to edit this same activity: 

4.  Note the error message: "Unfortunately, the selected content type 'H5P.DragText 1.8' isn't installed on this system."

5.  Attempt to edit remaining questions.   Observe similar messages for different question types eg: 

"Unfortunately, the selected content type 'H5P.MultiChoice 1.14' isn't installed on this system."

6.  Review the installed libraries at: /mod/hvp/library_list.php

7.  Note that the referenced libraries do indeed exist

 

**Steps to replicate #2 - Creating a new H5P**

1.   In any course, add a new 'Interactive Content (H5P)' activity.

2.   Add 'Quiz (Question set)'

3.   Attempt to add a question.   Notice that the 'Question Type' dropdown is empty

 

 

**Mobile or Desktop**:  Desktop

**Browser**: Chrome, Firefox and Safari  - 

**H5P plugin version**: 2020020500

**Errors:** "Unfortunately, the selected content type 'H5P.DragText 1.8' isn't installed on this system."

**Comment by thomasmars** [comment]
Were you able to resolve this ? This happens if H5P is not able to find the library that you're requesting on the backend or if the client is not able to communicate with the backend for whatever reason. Please check for any php errors or browser console errors, and ensure that the libraries are properly installed and can be used normally when creating content.
