### ISSUE TITLE
Editor doesn't open at all in Moodle, [field:group:coursepresentation:presentation]

### ISSUE THREAD

**Issue by Urpokarhu1** [h5p/moodle-mod_hvp#362]
Hello,

We are having trouble with mod_hvp 1.20.1 (2019111300) and Moodle 3.5.4, we have community hub disaled in this Moodle (for security purposes).

When you add a new course presentation or interactive video editor doesn't open at all.

- Course presentation gives an error:
- [field:group:coursepresentation:presentation]
- Interactive video gives an error:
- [field:group:interactivevideo:assets]
- what is causing this?

![coursprese](https://user-images.githubusercontent.com/53904029/91028949-d5d63900-e606-11ea-8fa9-4d842710076d.png)

<img width="533" alt="intvideo" src="https://user-images.githubusercontent.com/53904029/91028957-d8d12980-e606-11ea-9171-3a196b7e14cd.png">

**Comment by thomasmars** [comment]
This can happen if you're missing a library. Check that your libraries are properly installed, e.g. reinstall Course Presentation and Interactive Video for instance by re-uploading them from H5P.com as an admin with `$CFG->mod_hvp_dev = '1';` set in your config.
You can also enable [Moodle debugging](https://docs.moodle.org/39/en/Debugging) to see if you're getting any PHP errors.

**Comment by Urpokarhu1** [comment]
Thanks for the tip, we will try this.

**Comment by satodu** [comment]
Any news with this issue, I am getting same error :)

**Comment by thomasmars** [comment]
Hi Satodu, did you try the proposed solution ?
Please open a separate issue with more info if you're still having problems.
