### ISSUE TITLE
TypeError: e.contentTypes is undefined - Installing Interactive Video / Course Presentation

### ISSUE THREAD

**Issue by Pablo849** [h5p/moodle-mod_hvp#365]
I can't install Interactive Video and Course Presentation content types. When I try, "TypeError: e.contentTypes is undefined" is raised in browser console. Other content type (Column,  Image Hotspot, ...) install without problems.

Browser: Safari, Chrome, Mozilla
OS: Ubuntu, OS X

Moodle: 3.9.1+
mod_hvp: 1.21 / 1.20.2
PHP: 7.2
MariaDB

PHP Error log:

[Wed Sep 09 12:51:21.303961 2020] [fcgid:warn] [pid 30656] [client  *******:49460] mod_fcgid: stderr: PHP Warning:  Error while sending QUERY packet. PID=30346 in /*****/public_html/lib/dml/mysqli_native_moodle_database.php on line 1272,  
[Wed Sep 09 12:51:21.303991 2020] [fcgid:warn] [pid 30656] [client  *******:49460] mod_fcgid: stderr: Default exception handler: Error al leer de la base de datos Debug: MySQL server has gone away,  
[Wed Sep 09 12:51:21.303999 2020] [fcgid:warn] [pid 30656] [client  *******:49460] mod_fcgid: stderr:                 SELECT id,  
[Wed Sep 09 12:51:21.304004 2020] [fcgid:warn] [pid 30656] [client  *******:49460] mod_fcgid: stderr:                   FROM mdl_hvp_libraries,  
[Wed Sep 09 12:51:21.304010 2020] [fcgid:warn] [pid 30656] [client  *******:49460] mod_fcgid: stderr:           WHERE machine_name = ? AND major_version = ? AND minor_version = ?,  
[Wed Sep 09 12:51:21.304015 2020] [fcgid:warn] [pid 30656] [client  *******:49460] mod_fcgid: stderr:               ORDER BY major_version DESC,,  
[Wed Sep 09 12:51:21.304020 2020] [fcgid:warn] [pid 30656] [client  *******:49460] mod_fcgid: stderr:                        minor_version DESC,,  
[Wed Sep 09 12:51:21.304035 2020] [fcgid:warn] [pid 30656] [client  *******:49460] mod_fcgid: stderr:                        patch_version DESC,  
[Wed Sep 09 12:51:21.304041 2020] [fcgid:warn] [pid 30656] [client  *******:49460] mod_fcgid: stderr:                  LIMIT 0, 1,  
[Wed Sep 09 12:51:21.304046 2020] [fcgid:warn] [pid 30656] [client  *******:49460] mod_fcgid: stderr: [array (,  
[Wed Sep 09 12:51:21.304050 2020] [fcgid:warn] [pid 30656] [client  *******:49460] mod_fcgid: stderr:   0 => 'Drop',,  
[Wed Sep 09 12:51:21.304055 2020] [fcgid:warn] [pid 30656] [client  *******:49460] mod_fcgid: stderr:   1 => 1,,  
[Wed Sep 09 12:51:21.304060 2020] [fcgid:warn] [pid 30656] [client  *******:49460] mod_fcgid: stderr:   2 => 0,,  
[Wed Sep 09 12:51:21.304064 2020] [fcgid:warn] [pid 30656] [client  *******:49460] mod_fcgid: stderr: )],  
[Wed Sep 09 12:51:21.304069 2020] [fcgid:warn] [pid 30656] [client  *******:49460] mod_fcgid: stderr: Error code: dmlreadexception,  
[Wed Sep 09 12:51:21.304074 2020] [fcgid:warn] [pid 30656] [client  *******:49460] mod_fcgid: stderr: * line 486 of /lib/dml/moodle_database.php: dml_read_exception thrown,  
[Wed Sep 09 12:51:21.304078 2020] [fcgid:warn] [pid 30656] [client  *******:49460] mod_fcgid: stderr: * line 1273 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end(),  
[Wed Sep 09 12:51:21.304083 2020] [fcgid:warn] [pid 30656] [client  *******:49460] mod_fcgid: stderr: * line 625 of /mod/hvp/classes/framework.php: call to mysqli_native_moodle_database->get_records_sql(),  
[Wed Sep 09 12:51:21.304097 2020] [fcgid:warn] [pid 30656] [client  *******:49460] mod_fcgid: stderr: * line 3069 of /mod/hvp/library/h5p.classes.php: call to mod_hvp\\framework->getLibraryId(),  
[Wed Sep 09 12:51:21.304101 2020] [fcgid:warn] [pid 30656] [client  *******:49460] mod_fcgid: stderr: * line 1576 of /mod/hvp/library/h5p.classes.php: call to H5PCore->getLibraryId(),  
[Wed Sep 09 12:51:21.304123 2020] [fcgid:warn] [pid 30656] [client  *******:49460] mod_fcgid: stderr: * line 1518 of /mod/hvp/library/h5p.classes.php: call to H5PStorage->saveLibraries(),  
[Wed Sep 09 12:51:21.304128 2020] [fcgid:warn] [pid 30656] [client  *******:49460] mod_fcgid: stderr: * line 279 of /mod/hvp/editor/h5peditor-ajax.class.php: call to H5PStorage->savePackage(),  
[Wed Sep 09 12:51:21.304137 2020] [fcgid:warn] [pid 30656] [client  *******:49460] mod_fcgid: stderr: * line 116 of /mod/hvp/editor/h5peditor-ajax.class.php: call to H5PEditorAjax->libraryInstall(),  
[Wed Sep 09 12:51:21.304151 2020] [fcgid:warn] [pid 30656] [client  *******:49460] mod_fcgid: stderr: * line 287 of /mod/hvp/ajax.php: call to H5PEditorAjax->action(),

**Comment by thomasmars** [comment]
Your server is not able to read from your database. Please enable [debugging](https://docs.moodle.org/39/en/Debugging) to see which php errors you're getting and check your database to see which errors you're getting there.
This could be caused by a range of different configuration issues.

**Comment by Pablo849** [comment]
Solved. The error was in the MariaDB configuration, the wait_timeout parameter was configured for 10 seconds, so with lighter packages it did not give installation problems. Uploaded to 60 seconds and installed without problem. Many Thanks.
