### ISSUE TITLE
Non-unique index for mdl_hvp_xapi_results

### ISSUE THREAD

**Issue by haietza** [h5p/moodle-mod_hvp#367]
Was the index on mdl_hvp_xapi_results intentionally designed to be unique for a specific reason?

It seems as though using the id column, which is unique all by itself, included with the content_id and user_id doesn't offer any added benefit. It also prevents some queries that are used in the plugin from being able to use the index.

We were seeing significantly slow query times on this one from the review.php page, for example:

SELECT x.*, i.grademax
FROM mdl_hvp_xapi_results x
JOIN mdl_grade_items i ON i.iteminstance = x.content_id
WHERE x.user_id = ''
AND x.content_id = ''
AND i.itemtype = 'mod'
AND i.itemmodule = 'hvp';

**Comment by thomasmars** [comment]
Yes, looks like you're correct. We would appreciate a pull request.

**Comment by tellotello** [comment]
We see lots of slow query logs on db :

DELETE FROM mdl_hvp_xapi_results WHERE content_id = '' AND user_id = '' 

Is this also related with this issue? Do you have a plan to make a new release soon?

**Comment by thomasmars** [comment]
This is merged in and will be part of the next release assuming we dont find any issues with it
