### ISSUE TITLE
Download package not updating when activity is updated

### ISSUE THREAD

**Issue by phil-r-openlms** [h5p/moodle-mod_hvp#371]
Summary:
After an h5p activity is created and the package has been downloaded, updating the content in the activity seemingly does not cause the download package to regenerate with the updated data. This means downloading the package using the 're-use' link doesn't accurately reflect the content inside the activity. I have only tested thus far with a Course Presentation, so am not sure if it is isolated to this content type or also affects others.

Environment details:
Moodle Version: 3.7.7
H5P plugin version: 1.20.2 (2020020500)
H5P content type and version: Course Presentation (1.22.0)

Steps to reproduce:
1. In Moodle, add a new h5p activity
2. Choose the course presentation
3. Add a slide
4. Add an image to the slide
5. Ensure 'Allow download' is ticked
6. Save and display
7. Click the 'Re-use' link at the bottom left and then 'download as an .h5p file'
8. Wait for the file to generate and download. On your computer note the filesize
9. Edit the h5p activity and add an additional slide with another different image (repeat steps 2-6)
10. Repeat step 7 and 8

Observed behaviour:
The h5p package file generated is the same size regardless of how much content you add in. Adding more images should increase the package size. Restoring this file to an h5p activity causes it to display the initial activity that was created with only one image i.e. the package file is not updating when the content is updated.

Expected behaviour:
When content is changed within the h5p activity, the h5p package file is re-generated to produce an updated backup file

**Comment by thomasmars** [comment]
@phil-r-openlms Thannks for reporting this.
Could you check if this is a cache issue ? e.g. by disabling the cache in your browser and then try to do the same steps ?
You can disable cache in chrome by clicking the "disable cache" checkbox in the network tab, see https://developers.google.com/web/tools/chrome-devtools/network/reference#change_loading_behavior
