### ISSUE TITLE
Deleting activity with main library missing

### ISSUE THREAD

**Issue by montypanday** [h5p/moodle-mod_hvp#374]
Summary:
A course can be restored with H5P activities with the associated library not installed. When such activities with missing libraries are deleted, the adhoc tasks never completes because of problem with hvp_events table constraints.

Environment details:
Moodle Version: 3.5.4
H5P plugin version: 1.20.2 (2020020500)

Steps to reproduce:
Backup a course with atleast 1 hvp activity
Remove the Library used
Restore the course from backup
Try to delete the hvp activity in restord course

Observed behaviour:
When a course is restored with H5P activities which have libraries not installed in the Moodle, the main_library_id is set to 0. 
 When trying to delete this activity, an adhoc task of type \core_course\task\course_delete_modules is scheduled. This adhoc task tries to delete this activity, successfully deletes it but when trying to log an event tries to log null in library_name and library_version. The database table hvp_events have not null constraint on these columns. 
As such the activity is deleted, event is not fired and adhoc task keeps on retrying.

Expected behaviour:
Moodle should allow to delete h5p activities which do not have main library

I am happy to submit a PR if I can get some feedback on this.

**Comment by montypanday** [comment]
This will also behave the same way if major or minor version don't match. Maybe the Restore process should offer to upgrade activities to new versions if possible.

**Comment by montypanday** [comment]
#375 Pull Request raised

**Comment by thomasmars** [comment]
Thanks for reporting this. To me it seems like the problem is loss of data integrity when restoring a backup, you should not be able to upload or import if the H5P library is not already installed or not installable from the .h5p file. You should not be able to have content that can not be viewed/is missing required library dependencies.
Have you checked why the library is not installed when restoring the backup ? Are you using `mod_hvp_backup_libraries='0'` ?

**Comment by thomasmars** [comment]
I added a fix that does not dispatch a `'content delete'` event if the library is not found.

**Comment by thomasmars** [comment]
Ideally the database should never be in a state where content is uploaded that you don't have the libraries to show.
