### ISSUE TITLE
Resize script

### ISSUE THREAD

**Issue by J-Lenthall** [h5p/moodle-mod_hvp#381]
Apologies if this isn't the correct place to ask, I'm a noob when it comes to GIT.

Is there a reason <script src="https://moodle.port.ac.uk/mod/hvp/library/js/h5p-resizer.js" charset="UTF-8"></script> isn't added to a moodle page by default when theres H5P content?

Thank you

**Comment by thomasmars** [comment]
The resizing script is only necessary when embedding H5P content. Since we don't have control over the environment where H5P is embedded, the embedder (you) have to include the resizing script so that the iframe will resize appropriately where it is embedded.

**Comment by J-Lenthall** [comment]
Much appreciated ta
