### ISSUE TITLE
Grades are not saved from embedded H5P on first completion

### ISSUE THREAD

**Issue by Urpokarhu1** [h5p/moodle-mod_hvp#385]
Hello,

Grades are not saved from embedded H5P-activity on the first attempt, only on the second one.

Attached is problematic course and example h5p + video.

Tested with Moodle 3.5 & mod_hvp 1.21.0 & newest libraries.

steps to repeat:

1. Create course
2. Create H5P that 

- has drag text -question on the first slide
- on the second page it has true/false
- page 3 and page 4 are empty

3. Save and display

4. Embed the h5p on the course

5. open course as a "fresh" student account.

6. Answer on page1 to drag text and skip fast to the summary page

7. Check grader report as teacher/admin/manager and notice no grade is saved.

8. Answer second time as student

9. Check grader report as teacher/admin/manager and notice that this time grade is saved.

[h5pfile.zip](https://github.com/h5p/moodle-mod_hvp/files/5628721/h5pfile.zip)

[moodlecourse.zip](https://github.com/h5p/moodle-mod_hvp/files/5628722/moodlecourse.zip)

[video.zip](https://github.com/h5p/moodle-mod_hvp/files/5628728/video.zip)

**Comment by Urpokarhu1** [comment]
Hello,

Here is another course & h5p-activity that doesn't save grades on first "go through". I just created this course on Moodle Moodle 3.9.2+ (Build: 20201013)  & mod_hvp 1.21.0 although problem is with Moodle 3.5 also.

Attached is even better video showing what the problem is (first go through of embedded h5p doesn't save to grader report)

If you open the h5p-activity itself and complete it, this saves on the first go through so the problem lies within embedded h5p-activities.

[bettervideo.zip](https://github.com/h5p/moodle-mod_hvp/files/5651836/bettervideo.zip)

[example07122020.zip](https://github.com/h5p/moodle-mod_hvp/files/5651840/example07122020.zip)

[test-7-12-2020-23.zip](https://github.com/h5p/moodle-mod_hvp/files/5651845/test-7-12-2020-23.zip)

@thomasmars @fnoks

**Comment by thomasmars** [comment]
Thanks you for the detailed report.
I've made a fix at https://github.com/h5p/moodle-mod_hvp/commit/b9c7d86dc836cce688711f43db8198475585d86d, it will be released together with the content hub.

**Comment by Urpokarhu1** [comment]
Great!

**Comment by Urpokarhu1** [comment]
Hello,

Does this mean this will be updated with some library update that is released in near future?

**Comment by nenorojas** [comment]
@thomasmars , do you have any idea of when version 1.21.1 will be released for Moodle 3.9 with this fix? https://moodle.org/plugins/mod_hvp

**Comment by thomasmars** [comment]
I have no ETA, but we're working on the final stages of the content hub, which will be released for all our integrations, which will include the release for Moodle with this fix.
