### ISSUE TITLE
Essay Type content type throws error when viewing

### ISSUE THREAD

**Issue by barry-matthias** [h5p/moodle-mod_hvp#393]
Creating a new Essay h5p content activity throws the following debug trace

Exception - Call to a member function get_content() on boolean
More information about this error
Debug info:
Error code: generalexceptionmessage
Stack trace:

    line 258 of /mod/hvp/classes/file_storage.php: Error thrown
    line 2446 of /mod/hvp/library/h5p.classes.php: call to mod_hvp\file_storage->cacheAssets()
    line 188 of /mod/hvp/classes/view_assets.php: call to H5PCore->getDependenciesFiles()
    line 90 of /mod/hvp/classes/view_assets.php: call to mod_hvp\view_assets->getdependencyfiles()
    line 44 of /mod/hvp/view.php: call to mod_hvp\view_assets->__construct()

We checked and updated all the libs to make sure it wasnt the issue but when using

h5p module version 2020080400 named interactive content
and essay content example essay-4-166755.h5p
Creating the activity throws the debug trace shown  above and viewing the activity also throws the debug trace above.

It is very unclear how cached assets are implemented and how to either drop them or rebuild as you would expect when referring to caches.

Please look at this urgently as it is effecting 80 thousand students.

regards
BM

**Comment by thomasmars** [comment]
So the code fails when trying to generate cached assets.
This is because the system can not find the libraries that you're trying to cache. So somehow the libraries that you're trying to view the content for is missing.
I suggest trying to reinstall the library/libraries for this content.
