### ISSUE TITLE
Moodle 3.10: You do not have permission to view the content types

### ISSUE THREAD

**Issue by hdoug78** [h5p/moodle-mod_hvp#394]
Hi!
I get the following message at my Moodle 3.10 site: "You do not have permission to view the content types": I can't add any content at all because it seems that I can't get access to the library. I am logged in as an administrator with full permissions at my site. Anyone any idea what might cause this problem?

**Comment by thomasmars** [comment]
See https://docs.moodle.org/310/en/Permissions and mod/hvp:addinstance and mod/hvp:manage for your permissions for the request within the context you are in.

**Comment by hdoug78** [comment]
Hi Thomas! Thanks a lot!
Ok, I am a bit more familiar with the permissions now. But I can't find any mod/hvp permission at all or my administrator user role! I can find the "H5P" permission but there are NO entry for "HVP". The plugin is installed. Is it possible the the HVP Plugin isn't installed correctly?

**Comment by hdoug78** [comment]
Problem solved!!!!!!!!!
There was a problem at the installations process before. I had to specify the "plugin type" as an "activity"! No all the content types show up!
