### ISSUE TITLE
Default activity completions breaks module form

### ISSUE THREAD

**Issue by alexmorrisnz** [h5p/moodle-mod_hvp#396]
The course completion default settings data is stored in the table mdl_course_completion_defaults as json data under the column customrules.
When a user saves the related moodle form (`course/defaultcompletion.php?id=2` if you had a course with id 2, select H5P then the edit button) it adds a id value in the json array, this happens for every Moodle activity and it is expected behaviour.

mod_hvp does not handle this id value correctly when the data is then passed back into the editor form (Any form touching the mod/hvp/mod_form.php file, e.g. editing a H5P activity will be broken because of this).
See this snippet of code here:
https://github.com/h5p/moodle-mod_hvp/blame/51d1a9b54a35e3a962e52df7705b7c5bc12a79c6/mod_form.php#L182
When the id doesn't correlate to an existing H5P module, which it does not in the case of course completion defaults, the invalidhvp error is thrown and prevents users from adding new H5P activities to a course.

We have quite a few courses broken because of this bug, with teachers unable to add more H5P activities. There's no way for this completion default setting data to be deleted through the UI once set, so we have to make a code change to fix the resolve the issue for our courses.

**Comment by thomasmars** [comment]
Thanks for reporting this. I've made a fix at https://github.com/h5p/moodle-mod_hvp/commit/0d215a0439c98c14da5ce9b454615dc50ecd88dd that you could try. Let me know if there's still problems after applying this fix.
