### ISSUE TITLE
Fatal Error with release 1.22

### ISSUE THREAD

**Issue by aspark21** [h5p/moodle-mod_hvp#398]
Moodle: 3.9.6+ weekly release 20210416
mod_hvp: stable @ 9d9e785
PHP: 7.3

The stable branch has just taken months of worth of changes in one go - https://github.com/h5p/moodle-mod_hvp/compare/59d6605b2be7759f8aa48dd84e697109e060ba61...stable

When we run PHPUnit for our full build of Moodle we are now getting a fatal error with Moodle core H5P but nothing significant has changed in core in for months. So I'm tracking this down to the aforementioned big release

`PHP Fatal error:  Declaration of core_h5p\framework::fetchExternalData($url, $data = NULL, $blocking = true, $stream = NULL) must be compatible with H5PFrameworkInterface::fetchExternalData($url, $data = NULL, $blocking = true, $stream = NULL, $fullData = false, $headers = Array, $files = Array, $method = ''POST'') in /var/www/html/h5p/classes/framework.php on line 36'`

I see `$core->h5pF->` is used in places in this plugin & I assume this is where it's going wrong in using the core framework. 
[like here](
https://github.com/h5p/moodle-mod_hvp/compare/59d6605b2be7759f8aa48dd84e697109e060ba61...stable#diff-aa7234ef206b87c8443d4158b0c9d393887b8c4f5bf48ae2726c8c149842f43bR385)

**Comment by aspark21** [comment]
confirmed through separate runs of PHPUnit with just:
- core moodle
- core moodle & mod_hvp
That mod_hvp is the cause

**Comment by aspark21** [comment]
https://github.com/h5p/moodle-mod_hvp/blob/stable/classes/framework.php#L167 is where this fetchExternalData is implemented

The last change to it is here - https://github.com/h5p/moodle-mod_hvp/commit/a354066c73f2fb0a7013db6d96fcbb924320ffe7#diff-034e661161e9d56563de04b5f61b171f5b1cb30fcd50a7a60f667dbd1e15dd66R167

Which would hint towards the allData -> alldata  change as the cause

**Comment by aspark21** [comment]
intrigued by $fullData 

This doesn't exist in either Moodle core or mod_hvp codebase

**Comment by thomasmars** [comment]
Hi, we don't have control over Moodle's fork of H5P in core, so we can not ensure that the declaration matches what is in defined in our framework interface. The problem seems to be that H5PCore and Moodle's fork of H5PCore interface does not have separate namespaces, so if both files are loaded at the same time there is a problem. Does this manifest anywhere when actually using the plugin or is this purely a problem when running Moodle's CI suite ?

**Comment by thomasmars** [comment]
> intrigued by $fullData
> 
> This doesn't exist in either Moodle core or mod_hvp codebase

It is defined in the H5P Core framework interface: https://github.com/h5p/h5p-php-library/blob/master/h5p.classes.php#L33

**Comment by aspark21** [comment]
Thanks for looking at this so quickly though! 😄

**Comment by aspark21** [comment]
Fixed in core 3.11
