### ISSUE TITLE
Editor not loading with HTTPS enabled - Error 508

### ISSUE THREAD

**Issue by giacomogalliano** [h5p/moodle-mod_hvp#403]
I've installed the latest Moodle version (whitout any plugins) and the latest H5P plugin.
On my server i have activated the SSL before installing Moodle and H5P plugin.
When I choose some type of contents (For example: Interactive Video, Course Presentation, etcc ...) the server can't load editor js (It returned 508 error) and loading stuck.
I've tried to install to another webserver but it had returned the same error.
This problem appears only if i have enable https in moodle configuration.

Disabled the HTTPS in Moodle config, the editor loading perfectly and not showing error in browser console.
I've try to reinstall more times, convert to https (Using Moodle Tools), reinstall plugin but to no avail.
I've enabled debbugging mode, error logs, php error, but moodle don't show anything.
I have installed moodle on a lot of platforms and it worked fine on new installations until last year.
It is unthinkable in 2021 that we can only work in http. I need to enable SSL on entire site ASAP.
Tested on this version: 
Moodle Version: 3.10.3 (Latest)
H5P Moodle Plugin: 1.22.1 (Latest)
PHP Version: 7.4

Moodle Version: 3.9.1
H5P Moodle Plugin: 1.20.2
PHP Version: 7.4

This problem or similar, has already been reported in the following threads:

https://h5p.org/node/408442
https://h5p.org/node/922494
https://h5p.org/node/500002

Any solution? I am attaching the errors reported in the console.
Best regards,

Giacomo

[console_log.txt](https://github.com/h5p/moodle-mod_hvp/files/6383462/console_log.txt)
![h5p-plugin](https://user-images.githubusercontent.com/47320614/116219502-f9302580-a74b-11eb-894b-40a8c564221a.PNG)
![h5p-plugin-2](https://user-images.githubusercontent.com/47320614/116219503-f9c8bc00-a74b-11eb-8b11-3fddea114c54.PNG)

**Comment by thomasmars** [comment]
Hi, please see https://docs.moodle.org/310/en/Transitioning_to_HTTPS
In particular:

> However if you are using a proxy or load balancer, depending on your setup you may need to set $CFG->sslproxy to 1, and not use SSL on the Moodle server. Then the load balancer or proxy server can communicate directly to your Moodle site, but serve to the clients over SSL.

Could you try this ?

**Comment by giacomogalliano** [comment]
Hi @thomasmars ,
I have tried to enable sslploxy before opening this issue but nothing has changed.
It seems strange because I have been using H5P since 2018 and never had any problems until mid 2020. I was hoping this thing was fixed but sadly it is not. All testing was done on a clean install of moodle. I tried on two different hosting providers but got the same result.

**Comment by thomasmars** [comment]
Did you check the redirect settings for your server and proxy as well, as mentioned on that page ? https://docs.moodle.org/310/en/Transitioning_to_HTTPS
508 errors typically means that you have an error in the settings that are attempting to retrieve the files which makes the request redirect in an eternal loop.
Would you be able to share you moodle config, webserver config and proxy settings if you have these with any sensitive information stripped out, so we can attempt to reproduce this ?

**Comment by gallisiardi** [comment]
Same problem here.
Has anyone found a solution?

**Comment by Bellonio** [comment]
I have the same error. Only with HTTPS enabled.
Can anyone help me ?

**Comment by ghibux** [comment]
ciao ragazzi
I have also had this problem for a long time. We cannot work without SSL
Take a huge server machine only to manage an Moodle  with some courses it's not convenation to anyone

have you worked for this issue?

**Comment by icc** [comment]
I just set up Moodle on Ubuntu LTS on a virtual server. I installed nginx, php7.4-fpm, mariadb and certbot. I added the site config to nginx, ran certbot to get HTTPS, and then I ran through the standard moodle set up, downloaded and activated the H5P plugin. It was all straight and working.
Are you guys using some sort of special setup, an older version of Moodle or trying to convert an HTTP site to HTTPS?

**Comment by giacomogalliano** [comment]
Hi @icc,
I have tried with different versions of moodle.
Currently one of my many moodle installations is at version 3.9.1.
I tried on two different hosting and always got the same problem.
From what I can see the machine is saturated with running processes and therefore shows the error "Resource Limit Is Reached".
I can say that all the rest of the platform works fine, it just seems to have problems with the h5p module.
Obviously it is shown only with HTTPS enabled and I have not forced the HTTPS conversion as I have activated the platform already with the SSL certificate installed.
I already encountered this problem a year ago but I still have no solutions to solve it.

**Comment by icc** [comment]
If you try to open one of the failing(508) requests in a new tab, does it work?
Also, does it work for other files, tasks, or images uploaded through the Moodle filesystem? 
I suspect this is an internal redirect issue in moodle's file download system due to incompatible settings. E.g. HTTPS being forced but not properly configured for the URL or something like that.
What webserver are you using and have you configured any special rules? e.g. always redirect HTTP or HTTPS.

**Comment by giacomogalliano** [comment]
Yes, if I open one request at a time it works since what I had checked some time ago.
I have not configured any special rules for https. Thomas an H5P contributor had already checked my installation and there were no problems with the configuration.
However, I find it strange that a simultaneous queue of processes is created when the editor is loaded such that it causes the resource limit.

**Comment by icc** [comment]
Very strange that it works directly in a tab and not via the editor. Are you sure you aren't doing CORS? 
The queue of processes is normal as all of the asset files have to be authenticated and loaded via PHP since they can only be stored in  the moodledata folder(which is not available for the web). However, you should ensure your web server/system supports and have enabled sendfile to allow the web server to stream the file instead of PHP. Ref. https://docs.moodle.org/311/en/Performance_recommendations#X-Sendfile

**Comment by giacomogalliano** [comment]
Hi @icc,
I tried to enable X-sendfile but nothing has changed.
In any case moodle does not load the js causing the editor to load endlessly.
Do you have any other solution on this?
I reiterate the fact that this problem is present only on new versions of moodle (With HTTPS).
If you are willing to help me I can provide you with access to a moodle installation that has this problem.
Thanks for the support,
Giacomo
