### ISSUE TITLE
Display Action bar and frame disabling does not get saved

### ISSUE THREAD

**Issue by gemguardian** [h5p/moodle-mod_hvp#407]
**Version plugin:1.22.2 (2021043000) **
**Moodle site: 3.9 and 3.10**
**PHP: 7.3**

**Issue**
When I enable "display action bar and frame" in my H5P activity and save. I see the action bar. 
When I go back to the activity settings, disable the setting "display action bar and frame", save. I still see the action bar. When I go back to activity settings the "display action bar..." setting is enable even though I disabled it before. 

**Video*
I created a video so it is easier to replicatie: https://vimeo.com/552833443/52d5e73ef7

**Comment by thomasmars** [comment]
Should be fixed by https://github.com/h5p/moodle-mod_hvp/commit/739de9ffb77f9b94c23a13c3d869ea4040b1760b
