### ISSUE TITLE
Error writing to database

### ISSUE THREAD

**Issue by vgulshan1985** [h5p/moodle-mod_hvp#408]
Hello 

I am new to moodle and H5p  Plugin I need your help

when I try to add a new question with the h5p plugin content 
editor, not loading 

the error is coming  Error writing to the database 
 I have already increased the size of the packet

please provide me a solution ASAP

**{"error":"Error writing to database","errorcode":"dmlwriteexception","stacktrace":null,"debuginfo":null,"reproductionlink":null}**

**Comment by thomasmars** [comment]
Hi.
Please provide php stack trace, database debug info and steps to reproduce this if it is a problem with the plugin.
See https://docs.moodle.org/311/en/Debugging for enabling debugging in Moodle.
