### ISSUE TITLE
Error exception, too few arguments while trying to embed content.

### ISSUE THREAD

**Issue by melnox** [h5p/moodle-mod_hvp#409]
Receiving the following error when embedding content
"Exception - Too few arguments to function page_requirements_manager::js_call_amd(), 1 passed in [dirroot]/mod/hvp/embed.php on line 94 and at least 2 expected"

**Comment by thomasmars** [comment]
See https://github.com/h5p/moodle-mod_hvp/pull/410

**Comment by nenorojas** [comment]
Hi @thomasmars , we are having this issue with Moodle 3.5.18 using version of plugin 1.22.3. 

I think that to avoid confusion, the version for 3.5 to 3.8 could be different from 3.9 onwards:
![image](https://user-images.githubusercontent.com/3680797/131327578-ff14fe8a-934e-4e7f-b960-f1826b0a96ca.png)

**Comment by mgancarzdsi** [comment]
We updated to h5p mod version 1.22.3 in our Moodle 3.5 (also updating soon) since it was indicated as compatible, but now we need to roll back the hvp plugin version because of this breaking change.

Please update the plugin directory and your version.php requires file.

**Comment by thomasmars** [comment]
Sorry to hear this, I've updated the supported versions on the plugin page for Moodle. Will update the plugin version dependency in the codebase on the next release unless we find a way to make this backwards compatbile.

**Comment by mgancarzdsi** [comment]
Thank you @thomasmars , I deleted my comment regarding the compatibility issue on there to avoid confusing people looking at it in the future.

**Comment by nenorojas** [comment]
Thanks @thomasmars for adjusting for 3.5. What I understood is that version 1.22.3 will break embed on Moodle 3.6, 3.7 and 3.8 as well. If that's the case, would be great to mention 1.22.2 for the other versions as well. Cheers
