### ISSUE TITLE
Branching Scenario stops working after update

### ISSUE THREAD

**Issue by alishanov** [h5p/moodle-mod_hvp#413]
Branching Scenario content type stops working after applying update within the module. The start button is not responding, clearing the cache does not help. Affected are both already existing and newly created activities.
<img width="467" alt="bs" src="https://user-images.githubusercontent.com/4518554/122130827-36d53480-ce06-11eb-9019-02e208f8fa91.PNG">

**Comment by fnoks** [comment]
Would it be possible for me to see this myself? If so, could you send me a link to pal.jorgensen(at)gmail.com?

If not, could you please answer the following questions?
- Are there any errors in the JavaScript console? If so, please paste it here.
- Which browser + version are you using?

**Comment by alishanov** [comment]
Thank you for the prompt response and fixing the issue!

**Comment by fnoks** [comment]
For the record: this was a bug in Branching Scenario, which was fixed in version 1.5.4 of the H5P.BranchingScenario ibrary. Ref: https://h5p.org/post-hub-releases
