### ISSUE TITLE
Unable to edit text for Course Presentation 

### ISSUE THREAD

**Issue by dsiroumi** [h5p/moodle-mod_hvp#417]
Hi,

I am using Moodle 3.9, i cannot edit text in a course presentation. Steps to reproduce are as follows: 

1. Create h5p activity and add a course presentation
2. Add a text (All works fine until here)
3. Go to edit settings and try to edit the text (Change colour or font etc - the dropdown blinks and i cannot change anything)
4. Click on done then try to edit again
5. From here i am unable to save or remove unless i refresh the page again.

Please see screen recording.

https://user-images.githubusercontent.com/25928363/124266082-68e8d500-db2e-11eb-8cb1-d0eec89c7039.mp4

**Comment by thomasmars** [comment]
Which version of Course Presentation are you using ? Have you tried to update it ?

**Comment by dsiroumi** [comment]
@thomasmars thank you! We were using Course Presentation (1.17.10). I upgraded to 1.22.3 and this issue is now fixed.
