### ISSUE TITLE
Fatal Error when installing latest version

### ISSUE THREAD

**Issue by Fae6068123** [h5p/moodle-mod_hvp#420]
Warning: require_once(C:\Apache24\htdocs\moodle/mod/hvp/library/h5p.classes.php): failed to open stream: No such file or directory in C:\Apache24\htdocs\moodle\mod\hvp\autoloader.php on line 77

Fatal error: require_once(): Failed opening required 'C:\Apache24\htdocs\moodle/mod/hvp/library/h5p.classes.php' (include_path='C:\Apache24\htdocs\moodle/lib/pear;.;c:\php\includes') in C:\Apache24\htdocs\moodle\mod\hvp\autoloader.php on line 77

**Comment by thomasmars** [comment]
Make sure you have checkout out the submodules like the readme says: https://github.com/h5p/moodle-mod_hvp/blob/stable/README.md

**Comment by Fae6068123** [comment]
The fix does not work. It appears it fails to load libraries.

**Comment by nise** [comment]
Same here! The branches master, release and stable are broken. 

It would be nice if someone could take a look into this since many deployment pipline will be broken because of this error.

**Comment by icc** [comment]
If you `cd mod/hvp/library/` what does `git status` say?

**Comment by nise** [comment]
As suggested before, the submodules were missing. 

It would be nice to test the existence of the required submodules in the code in order to provide a proper error message including an instruction on how to resolve the problem. In addition, the required submodules could be mentioned in the readme.md

**Comment by thomasmars** [comment]
They are mentioned: https://github.com/h5p/moodle-mod_hvp/blob/stable/README.md#usage
