### ISSUE TITLE
Description is twice on the activity page (4.0)

### ISSUE THREAD

**Issue by anjolaat** [h5p/moodle-mod_hvp#450]
Is it a bug or a feature that the description is shown twice on the activity page? Just upgraded Moodle to 4.0.1. 
The first is on the gray background with the completion progress requirements and the second is right after that with the white background. I assume that there should be description only once before the actual H5P content?

![image](https://user-images.githubusercontent.com/6739027/173009129-f67deda4-bb94-418b-979f-9834b19a59a0.png)

**Comment by zstoimenov** [comment]
I encountered that as well. Happy to see that @anjolaat has reported it already.
I used Raw SCSS to hide the second description as a quick measure but it needs to be fixed by the developer.
/* Hide the doubling of the description on H5P activities */
div#hvpintro.box.py-3.mod_introbox {
  display: none!important;
}

**Comment by anopraxis** [comment]
It would be really great if this was fixed

**Comment by idiomasocw** [comment]
Thank you @lucaboesch. Your code update for the view.php file resolved the issue.

**Comment by Fbornemann** [comment]
I tried inserting your code to SCSS [zstoimenov](https://github.com/zstoimenov) but it still doubles:


<img width="1206" alt="Skærmbillede 2023-09-04 kl  10 06 07" src="https://github.com/h5p/moodle-mod_hvp/assets/54360558/afab6e64-9ec4-48b7-a2fa-7d1fbc69a3a0">

<img width="843" alt="Skærmbillede 2023-09-04 kl  10 07 08" src="https://github.com/h5p/moodle-mod_hvp/assets/54360558/ff69a5e3-d2d6-4cf7-9bc4-5c9c4c59558f">

What am I doing wrong? And does anybody know if an official fix is on the way?

Kind regards 
Flemming Bornemann

**Comment by robertliu-preece** [comment]
I've just hit this problem of a repeated description on an H5P activity I made through Moodle.  Any suggested solutions?

![Screenshot 2024-01-18 144906](https://github.com/h5p/moodle-mod_hvp/assets/157035562/660a5608-55bb-4496-bda4-fc7b77cd1fd9)
