### ISSUE TITLE
Editor breaking when attempting to update content types

### ISSUE THREAD

**Issue by marxjohnson** [h5p/moodle-mod_hvp#453]
Steps to reproduce (PHP 8):

1. Add a new Interactive Content activity to a course
2. In the "Editor" field, find a content type showing "Update available"
3. Click "Details"
4. Click "Update"
5. Expected: the content type is updated. Actual: The editor disappears.

Inspecting the AJAX request that is called when the button is pressed, it is failing with an exception:
```
Exception - chmod(): Argument #1 ($filename) must be of type string, resource given
* line 247 of /mod/hvp/classes/framework.php: TypeError thrown
* line 247 of /mod/hvp/classes/framework.php: call to chmod()
* line 415 of /mod/hvp/editor/h5peditor-ajax.class.php: call to mod_hvp\framework->fetchExternalData()
* line 307 of /mod/hvp/editor/h5peditor-ajax.class.php: call to H5PEditorAjax->callHubEndpoint()
* line 133 of /mod/hvp/editor/h5peditor-ajax.class.php: call to H5PEditorAjax->libraryInstall()
* line 289 of /mod/hvp/ajax.php: call to H5PEditorAjax->action()
```
If appears that `$stream` is set to the output of `fopen()` (`false` or a resource) before being passed to `chmod()`, but `chmod()` only accepts strings. This is causing an exception on PHP 8.

**Comment by marxjohnson** [comment]
I will work on this fix today and provide a pull request.

**Comment by marxjohnson** [comment]
GitHub doesn't seem to be linking my Pull Request to this issue, so here it is:
https://github.com/h5p/moodle-mod_hvp/pull/455

**Comment by Mask66** [comment]
Seeing this on initial install of content types too, any chance that the fix lands anytime soon? Works like a charm after applying the changes in the pull request...
