### ISSUE TITLE
Editor breaking when installing new content type

### ISSUE THREAD

**Issue by bkasel** [h5p/moodle-mod_hvp#465]
environment:
php 8.0 moodle 4.0.2 hvp-plugin:1.22.3 and 1.22.4 tested in multiple browsers

When creating a new h5p activity instaling a new content type fails (clicking get and then install in th editor), the editor breaks and disappears. The following error is displayed in the browser js console.

![grafik](https://user-images.githubusercontent.com/16179803/185714679-b2c6151e-f500-40f8-adf5-1fe28962437d.png)

**Comment by bkasel** [comment]
The error was remedied by changing to php version 7.4. It seems that the editor is not php 8.0 compatible yet.

**Comment by DmitrySharabin** [comment]
Hey there! 👋🏻

I'm facing the same issue. Is there any workaround for it?

**Comment by cairiza** [comment]
El plugin H5P en Moodle, se cuelga instalando --- tipo de contenido, SOLUCION, Usar php 7.4

**Comment by cairiza** [comment]
> changing to php version 7.4.

**Comment by sanjuanbosco** [comment]
Estimados, 
no es necesario cambiar de versión de PHP. Es un problema de permisos de archivos que se arregla cambiando algunas líneas del: ./mod/hvp/classes/framework.php

En adjunto se los envío. Los cambios están indicados con "MARCA".
Saludos.
+Andrés

**Comment by zabellemotte** [comment]
I confirm the patch proposed by ing-andres-lopez works but it would be great to apply it to the main project because PHP 7.4 is no more supported.

**Comment by fjrojast** [comment]
> Estimados, no es necesario cambiar de versión de PHP. Es un problema de permisos de archivos que se arregla cambiando algunas líneas del: ./mod/hvp/classes/framework.php
> 
> En adjunto se los envío. Los cambios están indicados con "MARCA". Saludos. +Andrés
> 
> framework.php (https://github.com/h5p/moodle-mod_hvp/files/10564748/framework.php.patch)

Excelente. funcionó perfectamente. / Great, it works!

Muchas gracias / Thank you.

**Comment by benfes** [comment]
I believe that this is the same issue as mentioned here: https://github.com/h5p/moodle-mod_hvp/issues/471

The patch attached to that ticket should fix the issue you're experiencing: https://github.com/h5p/moodle-mod_hvp/pull/472

**Comment by icc** [comment]
Fixed by #472 will release an updated plugin asap.

**Comment by zabellemotte** [comment]
If you want to make the mimimal maintenance for this plugin, it would be great to integrate the Moodle 4 new icon. It is only 2 lines to modify.
https://docs.moodle.org/dev/Moodle_4.0_developer_update#Activity_icons
