### ISSUE TITLE
Problem interactive H5P MOODLE 4.1.1+

### ISSUE THREAD

**Issue by Dylan8100** [h5p/moodle-mod_hvp#482]
Hello

I ask for help... I have moodle 4.1.1+ installed but since 4.1 the interactive h5p has been generating a problem for me, I cannot install any of its options when I enter the h5p menu I select the activity I need and when I click install the page reloads and the h5p interface disappears, leaving me unable to install the interactive aids.

I appreciate a help :c

![imagen_2023-02-06_111603530](https://user-images.githubusercontent.com/65318303/217025442-f4c50809-b56e-4567-a4eb-b275d7097b7d.png)
![imagen_2023-02-06_111636108](https://user-images.githubusercontent.com/65318303/217025555-eb3abe57-be06-434e-9aee-7d506163f976.png)
![image](https://user-images.githubusercontent.com/65318303/217025677-674ff947-b1a1-4ed8-ba34-933e6a751456.png)

**Comment by kameshfourbends** [comment]
Hi , 
I have same issue. I installed Moodle4.1.1+ in my local machine. I am using PHP8. I installed H5P creative content module. I try to create new content I got the same issue.
![image](https://user-images.githubusercontent.com/31654071/222639857-ece4ec6f-b9f4-4dc4-9c76-2d2be2e8d145.png)

![image](https://user-images.githubusercontent.com/31654071/222639923-d963a7b8-0e48-4a69-b95d-8e530b40532e.png)

please help any one to fix this issue.

**Comment by miftxh** [comment]
i have the same problem with my moodle 4.1....did you manage to fix this issue???

**Comment by officialbubies** [comment]
I have the same issue. I am running Moodle 4.1.1 on AWS EC2, using "Bitnami LMS by Moodle" AMI using Debian 11.

**Comment by aguatacuperche** [comment]
We have the same error both in version 4.1 and now in 4.2.
Bitnami 4.1.2 MariaDB 10.6.8 PHP 8.0.28
It also affects the updating of the libraries, not only their installation.
