### ISSUE TITLE
License is inconsistent with codebase

### ISSUE THREAD

**Issue by benfes** [h5p/moodle-mod_hvp#485]
I believe the license in the repo is out of sync, the PHP files list the licence as being GPL v3, however the license in this repo is GPL v2.

**Comment by thomasmars** [comment]
Thanks! Merged in.

**Comment by benfes** [comment]
Cheers @thomasmars - do you have any idea when a release on stable will be made with this change in it?

**Comment by benfes** [comment]
@thomasmars - Just following up,  is there a date to when this will be merged into the stable branch and have it added into a tagged release?
