### ISSUE TITLE
Description shown twice in view.php

### ISSUE THREAD

**Issue by winnidat** [h5p/moodle-mod_hvp#490]
There is a bug that the intro text (description) is shown twice at the View Page.
Tested with Moove and Boost Theme
<img width="768" alt="image" src="https://user-images.githubusercontent.com/26013011/225579351-17fb8a31-8342-4540-8ce2-8080e409df9d.png">

**Comment by otacke** [comment]
@winnidat Fixed by https://github.com/h5p/moodle-mod_hvp/pull/476

**Comment by otacke** [comment]
@winnidat You're welcome. Please note that this pull request still needs to be handled by the H5P core team.

**Comment by lucaboesch** [comment]
I don't think that's accurate and the pull request https://github.com/h5p/moodle-mod_hvp/pull/476 is valid.
