### ISSUE TITLE
Duplicate title in Quiz (question set) in moodle 4.1.2+

### ISSUE THREAD

**Issue by ho30hero** [h5p/moodle-mod_hvp#493]
Hello and hope you are well.
It seems that after updating to moodle 4.1.2 and also updating all plugins include H5P, in H5P's Quiz (question set) , we see the title is duplicated. Screenshot attached:
![h5p-duplicate-title-quiz](https://user-images.githubusercontent.com/13227182/229304490-8abf3d8d-aeff-4154-8d28-ed03b52b012e.png)
Php 7.4 - mariaDB 10.6
Kind Regards

**Comment by otacke** [comment]
See https://github.com/h5p/moodle-mod_hvp/pull/476
