### ISSUE TITLE
Problem after updating to version 2023122300 - 1.26.0

### ISSUE THREAD

**Issue by david-delco** [h5p/moodle-mod_hvp#528]
Hi everyone,

I became aware of the problem after upgrading to the new version of the Moodle plugin (2023122300 - 1.26), but I checked a second installation on a different server, it has not yet been upgraded and realized that the problem is the same.

I use H5P (black icon) in Moodle 4.1.4.

Basically, until at least two days ago, H5P activities were displayed correctly whether embedded in a label or displayed directly by clicking the activity.

Now unfortunately, regardless of the theme used and the course format, H5P activities are displayed small, in an unreadable format, which does not change even if I select full screen view.

Previously I noticed the presence of two error lines as per the attached image, but now they no longer appear.

I have cleared the Moodle caches and deleted the browser history, but to no avail.

H5P activities are not displaying as it should.

Can you help me with this? It would be a nice Christmas present ;-)

THANK YOU.
Happy holidays to all.
![Schermata 2023-12-24 alle 19 28 18](https://github.com/h5p/moodle-mod_hvp/assets/131487981/0b3f85c1-4583-490c-a52b-a6b709918170)

**Comment by DmitrySharabin** [comment]
I'm facing the same issue: the library CSS files don't load, so all the activities are broken. 😭 Had to revert to the previous release.

**Comment by falcon-git** [comment]
Does the new 1.26.1 work well for you?

**Comment by DmitrySharabin** [comment]
> Does the new 1.26.1 work well for you?

Unfortunately, after downloading the 1.26.1 source code and trying to install it, I get an error. So, there is no way for me to check whether the patch worked.

<img width="537" alt="SCR-20231225-ovid" src="https://github.com/h5p/moodle-mod_hvp/assets/9166277/6d7fcf00-7be5-41eb-87c4-6cc03d5504f4">

What am I doing wrong?

**Comment by david-delco** [comment]
Hi Falcon!
Thank you for this Christmas gift! The 1.26.1 release does work well for me.
I hope other users also find a solution.
Thanks again.
Happy Holidays
David

**Comment by DmitrySharabin** [comment]
> Does the new 1.26.1 work well for you?

It does for me as well. Thank you! ❤️

**Comment by danowar2k** [comment]
Maybe one could close this issue then?

**Comment by david-delco** [comment]
Yes, sorry! 👍🏻
