### ISSUE TITLE
Debug info: Unknown column 'h.content_type' in 'field list' when importing course

### ISSUE THREAD

**Issue by JoshB123456** [h5p/moodle-mod_hvp#569]
after upgrading hvp from 1.26.1 to 1.27 we are getting the following error when attempting to import course
Debug info: Unknown column 'h.content_type' in 'field list'
It looks like the upgrade is not creating the database columns required
created a copy of the site and run the following on its database and it appears to fix this issue
ALTER TABLE mdl_hvp ADD COLUMN `content_type` tinyint(1) DEFAULT 0

plugin version: 2024091200
moodle version '4.1.14 (Build: 20241007)';

**Comment by otacke** [comment]
Not an expert with moodle, but that column seems to have been set ever since (https://github.com/h5p/moodle-mod_hvp/blob/4b692cc1ba32b7d2fc1d237f8cce619cd5ed66bf/db/install.xml#L18)

**Comment by JoshB123456** [comment]
Looks like the issue is from moving between a custom repo of this back to this one where there looks like there was some modifications to the custom db structure for some reason
